spring:
  application:
    name: demo

  data:
    elasticsearch:
      cluster-name: productService
      cluster-nodes: localhost:9200

    mongodb:
      uri: mongodb+srv://nexus:nexus@phr.on1mb.mongodb.net/NexusEnterprise
      auto-index-creation: true
#server:
  #address: 0.0.0.0